# Generated by Django 5.2.8 on 2025-11-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='usb_access',
            field=models.BooleanField(default=False),
        ),
    ]
